### ISSUE TITLE
Entries are moving when changing slot size

### ISSUE THREAD

**Issue by MrEbbinghaus** [khrykin/StrategrDesktop#4]
When I have an entry starting at 10:00 with a slot size of 15min. When I change the slot size to 10min the entry is now starting at 9:20

**Comment by khrykin** [comment]
This is currently an expected behavior - when you change slot duration, the _session_  still belongs to the same _slot_, it is just the slot time that changes. So, it is probably better to set up your grid settings before you start planning, and you can always save your strategy as default  (cmd-D), and all new strategies will have these settings.

It's implemented this way because there is no way to preserve the session's time and duration if slots duration is downsized. For example, If I had 15 min session occupying one slot, and I would change the slot duration to 10 min, then there would be no way to place this 15 min session in two 10 min slots.

**Comment by MrEbbinghaus** [comment]
Wouldn't it be better to store the real time of a session? With minutes? 
You won't have to scale from 15min to 10min. Just leave them be. So the slot duration is only for user input. Not the logic itself.

**Comment by khrykin** [comment]
For me, the "sticking" algorithm was the reason I created this app because I was tired of moving events boundaries in conventional calendars while time boxing the whole day. This slot-based structure was a pretty simple and effective solution to this specific problem, I guess I just haven't came up with an algorithm that would provide sticking and at the same time would be timestamp-based, not slot-based. 

We might use the slot size of 1 min internally - this would practically solve the downsize problem, but this would require a significant rewrite of existing logic. Currently, my main goal is to bring existing functionality to other platforms, so after this phase, I might look into improving this.

**Comment by MrEbbinghaus** [comment]
I have to confess, that I am only able to really use the app, when there is bi-directional sync with a calendar. 

But I won't be able to provide anything in terms of code.

**Comment by khrykin** [comment]
I got your point, thank you, I will think about better calendar sync! 
In the next release, there will be an option to export to a specific calendar, so you can have all your appointments and events generated by Strategr side-by-side in Calendar.app (see #3), maybe this would improve your workflow.
However, please keep in mind that Strategr isn't intended to be a replacement for a calendar, there are no appointments, even dates - it is a time-boxing tool. It helps to solve not the "when something will be" type of problem, but more of "I have several things to do, how would I fit them into my day?" type - that's when it's most useful.
