### ISSUE TITLE
minimize to systray instead of closing the app

### ISSUE THREAD

**Issue by borco** [khrykin/StrategrDesktop#6]
Currently the app closes when you close the window. In my opinion, the app should just minimize to systray.

**Comment by khrykin** [comment]
We could do that, what exactly do you want to see in the tray menu?

**Comment by borco** [comment]
* from what I see, you usually get a menu when you click the systray icon
* you could show some info and have some menu entries bellow:
  * Info: name of the task, started at, finishing at, xx mins to go, ...
  * Menu: Show app window
  * Menu: Preferences...
  * Menu: Quit
* if possible, the icon should be:
  * gray if no task running
  * have the color of the running task, if a task is running

Here is a screenshot of how Fanny (https://github.com/DanielStormApps/Fanny) looks like:

![Screenshot 2020-02-08 at 20 27 51](https://user-images.githubusercontent.com/1324836/74090224-9a807c80-4ab1-11ea-8d83-53271a54a0f0.png)

**Comment by khrykin** [comment]
The problem is that, currently, there is no concept of _active_ strategy, i.e. _all_ opened strategies send notifications and in that sense are "active" (this is intended to be a feature, not a bug). If I've closed all the windows, what strategy is active now? 
So, currently, we could only basically show "Open New Window" in the tray menu and similar "dumb" items, which isn't very useful.  The concept of active strategy, however, would be required on the mobile, so we might revisit this when mobile apps get going.
